name: Windows build

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Run build
      run: References/Windows/scripts/build-all.bat

    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Installer
    #     path: desktop-app-ui\Windows\References\bin
